
name: Build and Deploy to OCI Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Check out repository
      uses: actions/checkout@v4

    - name: 2. Set up OCI API Config
      run: |
        mkdir -p ~/.oci
        echo -n "${{ secrets.OCI_PRIVATE_KEY }}" | base64 --decode > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        
        # Corrected 'giconfig' to 'config' and using 'vars' for region
        echo "[DEFAULT]" > ~/.oci/config
        echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
        echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
        echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
        echo "region=${{ vars.OCI_REGION }}" >> ~/.oci/config
        echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config

    - name: 3. Log in to OCI Container Registry (OCIR)
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.OCI_REGION_KEY }}.ocir.io
        username: ${{ secrets.OCI_TENANCY_NAMESPACE }}/${{ secrets.OCI_USERNAME }}
        password: ${{ secrets.OCIR_AUTH_TOKEN }}

    - name: 4. Set up Go and Build Fn CLI
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - run: |
        git clone https://github.com/fnproject/cli.git
        cd cli
        make build
        sudo mv fn /usr/local/bin/

    - name: 5. Configure and Verify OCI API Authentication
      run: |
        fn create context oci-prod --provider oracle
        fn use context oci-prod
        fn update context oracle.compartment-id "${{ secrets.OCI_COMPARTMENT_ID }}"
        fn update context api-url "https://functions.${{ vars.OCI_REGION }}.oci.oraclecloud.com"
        
        echo "--- Verifying OCI API Authentication ---"
        fn list apps
        echo "✅ OCI API Authentication Successful."

    - name: 6. Parse func.yaml and set Image Name
      id: parse_func
      run: |
        FUNCTION_NAME=$(grep '^name:' func.yaml | awk '{print $2}')
        FUNCTION_VERSION=$(grep '^version:' func.yaml | awk '{print $2}')
        APP_NAME="rag-app"
        
        echo "FUNCTION_NAME=${FUNCTION_NAME}" >> $GITHUB_ENV
        echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
        echo "FULL_IMAGE_NAME=${{ vars.OCI_REGION_KEY }}.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/${APP_NAME}/${FUNCTION_NAME}:${FUNCTION_VERSION}" >> $GITHUB_ENV

    - name: 7. Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.FULL_IMAGE_NAME }}

    - name: 8. Update OCI Function
      run: |
        echo "Updating function ${{ env.APP_NAME }}/${{ env.FUNCTION_NAME }} with image tag ${{ env.FULL_IMAGE_NAME }}"
        fn update function ${{ env.APP_NAME }} ${{ env.FUNCTION_NAME }} --image "${{ env.FULL_IMAGE_NAME }}"