
name: 'Provision Full Application Stack (Manual)'

on:
  workflow_dispatch:

env:
  APP_NAME: "app-rag"
  FUNCTION_NAME: "rag-ingestor"

jobs:
  provision-stack:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Check out repository
      uses: actions/checkout@v4

    - name: 2. Configure OCI and Fn Project CLIs
      run: |
        pip install --upgrade oci-cli
        mkdir -p ~/.oci
        printf "%s\n" "${{ secrets.OCI_PRIVATE_KEY_CONTENT }}" > ~/.oci/oci_api_key.pem
        echo "[DEFAULT]" > ~/.oci/config
        echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
        echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
        echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
        echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
        echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
        chmod 600 ~/.oci/oci_api_key.pem ~/.oci/config
        curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh

    - name: 3. Configure Fn Project CLI Context
      run: |
        fn create context oci-context --provider oracle --api-url "https://functions.${{ secrets.OCI_REGION }}.oci.oraclecloud.com" --registry "${{ secrets.OCI_REGION_KEY }}.ocir.io/${{ secrets.OCI_NAMESPACE }}"
        fn use context oci-context
        fn update context oracle.compartment-id "${{ secrets.OCI_COMPARTMENT_OCID }}"
        
    - name: 4. Log in to OCI Container Registry (OCIR)
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.OCI_REGION_KEY }}.ocir.io
        username: ${{ secrets.OCIR_USERNAME }}
        password: ${{ secrets.OCIR_AUTH_TOKEN }}

    - name: 5. Atomically Deploy Application and Function
      env:
        DB_SECRET_OCID: ${{ secrets.DB_SECRET_OCID }}
        OCI_NAMESPACE: ${{ secrets.OCI_NAMESPACE }}
        PUBLIC_SUBNET_OCID: ${{ secrets.PUBLIC_SUBNET_OCID }} # Make subnet available
      run: |
        # This single command now has all the information it needs from func.yaml
        fn --verbose deploy --app ${{ env.APP_NAME }} --create-app
    
    - name: 6. Enforce Network Security Groups (Robustness)
      run: |
        echo "Ensuring application is linked to the correct Network Security Group..."
        APP_OCID=$(oci fn application list --compartment-id ${{ secrets.OCI_COMPARTMENT_OCID }} --display-name "${{ env.APP_NAME }}" --query "data[0].id" --raw-output)
        NSG_IDS='["${{ secrets.FUNCTION_NSG_OCID }}"]'
        oci fn application update --application-id "$APP_OCID" --network-security-group-ids "$NSG_IDS" --force
        
    - name: 7. Wait for IAM Propagation
      run: |
        echo "Waiting 60 seconds for IAM service to recognize the new function..."
        sleep 60
        echo "Cooldown complete."